### ISSUE TITLE
Error in Release Mode

### ISSUE THREAD

**Issue by Fred0204** [HavenDV/H.NotifyIcon#18] opened 2022-04-21 07:42 UTC
### Describe the bug

I test Version 2.0.39 in Windows 10 and 11. I found that function works fine in Debug Mode. But crashed in Release Mode.

**Comment by HavenDV** [comment] 2022-04-22 17:00
I need any context to repeat the problem in order to solve it. Ideally, a project that works in Debug and doesn't work in Release.

**Comment by jonlester** [comment] 2022-04-22 23:54
I was having the same issue in 2.0.25.  However, after updating to 2.0.44 and setting the WindowHandle to an instance of MessageWindow, I no longer have the issue.  My project output is WinExe, but with no UI (basically a console app with no visible console).

**Comment by HavenDV** [comment] 2022-04-24 02:16
Please test this with version 2.0.45

> I was having the same issue in 2.0.25. However, after updating to 2.0.44 and setting the WindowHandle to an instance of MessageWindow, I no longer have the issue. My project output is WinExe, but with no UI (basically a console app with no visible console).

I also reverted the behavior that was there previously. Now a MessageWindow will be automatically created in case TrayIcon.WindowHandle is not set to make it easier to create a TrayIcon from the console.

**Comment by Fred0204** [comment] 2022-04-25 03:01
Thank you. In 2.0.46 every thing works great in windows 11. But the ToolTipText will crash in Windows 10. The error message is System.NullReferenceException: 'Object reference not set to an instance of an object.'. I build on Windows 10.

**Comment by jonlester** [comment] 2022-04-25 14:19
@HavenDV is there some part of the initialization that needs to be done on the UI thread? (ie, do I need to be certain that the window handle gets acquired from the owning thread).  Just asking to be certain.  I have not really looked at your code, but if I were to use some form of deferred initialization from an IoC container, I wanted to know if that would be a problem.  Thanks!

**Comment by jonlester** [comment] 2022-04-25 14:27
2.0.46 works for me too, even if I don't explicitly set the windowhandle.  I am on Windows 11, and have not tested with 10.

**Comment by HavenDV** [comment] 2022-04-25 17:06
> @HavenDV is there some part of the initialization that needs to be done on the UI thread? (ie, do I need to be certain that the window handle gets acquired from the owning thread). Just asking to be certain. I have not really looked at your code, but if I were to use some form of deferred initialization from an IoC container, I wanted to know if that would be a problem. Thanks!

I haven't encountered any problems accessing from another thread. I have also looked in detail at the Win32 API documentation for NotifyIcon and there is nothing there about this.
But I know that the console application has issues with receiving events. Its Message Window simply does not receive the necessary events, such as mouse clicks. Maybe it's somehow related.

**Comment by HavenDV** [comment] 2022-04-25 17:14
> Thank you. In 2.0.46 every thing works great in windows 11. But the ToolTipText will crash in Windows 10. The error message is System.NullReferenceException: 'Object reference not set to an instance of an object.'. I build on Windows 10.

Can you copy the source code of the library, point it to the project, and point to the point where this exception occurs? I've checked all the ToolTips code and don't see any options for NRE.
Either I need a sample application that reproduces the error.

**Comment by jonlester** [comment] 2022-04-25 21:06
Are you aware of any workarounds for getting the message window to receive events for a truly headless application?  Overall, your project is a great option for background processes that need minimal user interaction.  But being able to capture a mouse click event to display a menu would be required in almost any case I can think of.

**Comment by Fred0204** [comment] 2022-04-25 23:51
> > Thank you. In 2.0.46 every thing works great in windows 11. But the ToolTipText will crash in Windows 10. The error message is System.NullReferenceException: 'Object reference not set to an instance of an object.'. I build on Windows 10.
> 
> Can you copy the source code of the library, point it to the project, and point to the point where this exception occurs? I've checked all the ToolTips code and don't see any options for NRE. Either I need a sample application that reproduces the error.

This is my testing code

App.xml
```
<Application
    x:Class="ContextSensing.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:ContextSensing"
    xmlns:tb="using:H.NotifyIcon"
    >
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>

            <local:TaskbarData x:Key="TaskbarData"/>

            <tb:TaskbarIcon  x:Key="TaskbarIcon"
                             IconSource="ms-appx:///Images/logo.ico"
                             Visibility="Visible"
                             NoLeftClickDelay="True"
                             MenuActivation="RightClick"
                             ToolTipText = "Application Name"
                             >
                <tb:TaskbarIcon.ContextFlyout>
                    <MenuFlyout>
                        <MenuFlyoutItem Text="Open"
                                        />
                        <MenuFlyoutSeparator />
                        <MenuFlyoutItem Text="Exit"
                                        />
                    </MenuFlyout>
                </tb:TaskbarIcon.ContextFlyout>
            </tb:TaskbarIcon>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

App.xml.cs
```
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Controls.Primitives;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Navigation;
using Microsoft.UI.Xaml.Shapes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.ApplicationModel;
using Windows.ApplicationModel.Activation;
using Windows.Foundation;
using Windows.Foundation.Collections;
using H.NotifyIcon;

namespace Test
{
    public partial class App : Application
    {
        public static TaskbarIcon TaskbarIcon { get; set; }
        public App()
        {
            this.InitializeComponent();
        }

        protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {
            m_window = new MainWindow();
            m_window.Activate();

            TaskbarIcon = (TaskbarIcon)Resources["TaskbarIcon"];
            TaskbarIcon.ForceCreate();
        }
        private Window m_window;
    }
}
```

If I comment out ``` ToolTipText = "Application Name" ``` in App.xml, everything works great.

**Comment by HavenDV** [comment] 2022-04-26 08:50
> Are you aware of any workarounds for getting the message window to receive events for a truly headless application? Overall, your project is a great option for background processes that need minimal user interaction. But being able to capture a mouse click event to display a menu would be required in almost any case I can think of.

At the moment I don't know the reason for this behavior. It is possible that this is precisely due to the lack of a full-fledged UI thread and the corresponding Win32 calls that allow the process to receive the necessary messages. I created a feature issue so that you can keep track of when this feature will appear. I do not promise that it will be in the near future.

You can test the behavior in your particular case by subscribing to TrayIcon.MessageWindow.MouseEventReceived. If you get these events, you can use the H.NotifyIcon.PopupMenus package to create a context menu. Here is also a sample code using PopupMenu:
https://github.com/HavenDV/H.NotifyIcon/blob/23cb9fb9f2139fa196966ec78ac2f6efe23efcf7/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ContextMenu.cs#L214-L246

**Comment by HavenDV** [comment] 2022-04-26 09:41
> > > Thank you. In 2.0.46 every thing works great in windows 11. But the ToolTipText will crash in Windows 10. The error message is System.NullReferenceException: 'Object reference not set to an instance of an object.'. I build on Windows 10.
> > 
> > 
> > Can you copy the source code of the library, point it to the project, and point to the point where this exception occurs? I've checked all the ToolTips code and don't see any options for NRE. Either I need a sample application that reproduces the error.
> 
> This is my testing code
> 
> App.xml
> 
> ```
> <Application
>     x:Class="ContextSensing.App"
>     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>     xmlns:local="using:ContextSensing"
>     xmlns:tb="using:H.NotifyIcon"
>     >
>     <Application.Resources>
>         <ResourceDictionary>
>             <ResourceDictionary.MergedDictionaries>
>                 <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
>             </ResourceDictionary.MergedDictionaries>
> 
>             <local:TaskbarData x:Key="TaskbarData"/>
> 
>             <tb:TaskbarIcon  x:Key="TaskbarIcon"
>                              IconSource="ms-appx:///Images/logo.ico"
>                              Visibility="Visible"
>                              NoLeftClickDelay="True"
>                              MenuActivation="RightClick"
>                              ToolTipText = "Application Name"
>                              >
>                 <tb:TaskbarIcon.ContextFlyout>
>                     <MenuFlyout>
>                         <MenuFlyoutItem Text="Open"
>                                         />
>                         <MenuFlyoutSeparator />
>                         <MenuFlyoutItem Text="Exit"
>                                         />
>                     </MenuFlyout>
>                 </tb:TaskbarIcon.ContextFlyout>
>             </tb:TaskbarIcon>
>         </ResourceDictionary>
>     </Application.Resources>
> </Application>
> ```
> 
> App.xml.cs
> 
> ```
> using Microsoft.UI.Xaml;
> using Microsoft.UI.Xaml.Controls;
> using Microsoft.UI.Xaml.Controls.Primitives;
> using Microsoft.UI.Xaml.Data;
> using Microsoft.UI.Xaml.Input;
> using Microsoft.UI.Xaml.Media;
> using Microsoft.UI.Xaml.Navigation;
> using Microsoft.UI.Xaml.Shapes;
> using System;
> using System.Collections.Generic;
> using System.IO;
> using System.Linq;
> using System.Runtime.InteropServices.WindowsRuntime;
> using Windows.ApplicationModel;
> using Windows.ApplicationModel.Activation;
> using Windows.Foundation;
> using Windows.Foundation.Collections;
> using H.NotifyIcon;
> 
> namespace Test
> {
>     public partial class App : Application
>     {
>         public static TaskbarIcon TaskbarIcon { get; set; }
>         public App()
>         {
>             this.InitializeComponent();
>         }
> 
>         protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
>         {
>             m_window = new MainWindow();
>             m_window.Activate();
> 
>             TaskbarIcon = (TaskbarIcon)Resources["TaskbarIcon"];
>             TaskbarIcon.ForceCreate();
>         }
>         private Window m_window;
>     }
> }
> ```
> 
> If I comment out `ToolTipText = "Application Name"` in `App.xml`, everything works great.

I created a separate issue for this issue: https://github.com/HavenDV/H.NotifyIcon/issues/20
I guess I'll probably fix this as soon as I add support for native WinUI tooltips. So far, I still do not see a place in the code that could be problematic.
I repeat that you can speed up the process and help if you copy the library code or if you enable debugging not only your code (disable Just My Code).
![image](https://user-images.githubusercontent.com/3002068/165271621-8da1800c-2dc5-4495-a439-ecc3649b122d.png)

**Closed** 2022-05-24 04:52 UTC
Labels: bug
